spring:
  application:
    name: eureka
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/ # 注意： peer2要连接peer1的eureka地址
  server:
    peer-node-read-timeout-ms: 2000