spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/ # 注意： peer1要连接peer2的eureka地址
  server:
    peer-node-read-timeout-ms: 2000